// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package library

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-1]
	_ = x[DatabaseError-2]
	_ = x[BadInput-3]
	_ = x[InvalidSettings-4]
	_ = x[Timeout-5]
}

const _ErrorType_name = "UnknownDatabaseErrorBadInputInvalidSettingsTimeout"

var _ErrorType_index = [...]uint8{0, 7, 20, 28, 43, 50}

func (i ErrorType) String() string {
	i -= 1
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
