// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: create_book.sql

package sqlc

import (
	"context"
)

const createBook = `-- name: CreateBook :exec

INSERT INTO book (isbn, title)
VALUES ($1, $2)
`

type CreateBookParams struct {
	Isbn  int64
	Title string
}

// CreateBook creates a single book.
func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) error {
	_, err := q.db.Exec(ctx, createBook, arg.Isbn, arg.Title)
	return err
}
