// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: get_book.sql

package sqlc

import (
	"context"
)

const getBook = `-- name: GetBook :one

SELECT title, isbn FROM book WHERE isbn = $1
`

type GetBookRow struct {
	Title string
	Isbn  int64
}

// GetBook fetches a single book.
func (q *Queries) GetBook(ctx context.Context, isbn int64) (GetBookRow, error) {
	row := q.db.QueryRow(ctx, getBook, isbn)
	var i GetBookRow
	err := row.Scan(&i.Title, &i.Isbn)
	return i, err
}
