// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: update_book.sql

package sqlc

import (
	"context"
)

const updateBook = `-- name: UpdateBook :exec

UPDATE book SET title = $1 WHERE isbn = $2
`

type UpdateBookParams struct {
	Title string
	Isbn  int64
}

// UpdateBook updates a single book.
func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.Exec(ctx, updateBook, arg.Title, arg.Isbn)
	return err
}
